version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "server"
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "client"
    ports:
      - "3000:3000"
    links:
      - "server"
